name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: read 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Clone fray-gradle-plugin
        run: git clone https://github.com/cmu-pasta/fray-gradle-plugin.git
      - name: Publish fray-gradle-plugin to Maven Local
        run: |
          cd fray-gradle-plugin
          ./gradlew publishToMavenLocal
          cd ..
      - name: Build fray
        run: ./gradlew publishToMavenLocal
      - name: Build fray and run tests
        run: ./gradlew build
